export declare enum RNObjcSerialisableType {
  other = 0,
  void = 1,
  string = 2,
  nonnullString = 3,
  boolean = 4,
  nonnullBoolean = 5,
  number = 6,
  nonnullNumber = 7,
  array = 8,
  nonnullArray = 9,
  object = 10,
  nonnullObject = 11,
  RCTResponseSenderBlock = 12,
  RCTResponseErrorBlock = 13,
  RCTPromiseResolveBlock = 14,
  RCTPromiseRejectBlock = 15,
}
